### ISSUE TITLE
SWT-composites blink when StyledText is modified

### ISSUE THREAD

**Issue by gashmish** [iee/Position-Manager#10]
Problem description:
When new line is inserted into StyledText by user input, all it's child Composites moves down spontaneously. ContainerManager always reconsils Composite's locations, but only after receiving event from Document. So in some cases undesirable blinking Composites may appear at inproper locations for a short time when user performs modifications.

 For quick fix i added VerifyListener to StyledText, which sets all Composites to invisiable state. ContainerManager makes them visiable again. Composites still blinks, but at list at ther proper positions.

How can we solve this problem?
1) May be it's posiable to apply layouts to StyledText instead of calling Composite's SetBounds() method.
2) We can look for some ways to disable spontaneous Composite movement while StyledText modification.
3) Disable StyledText repainting until ContainerManager finishes it's work.

@khavrenko, i hope you can find the right way to fix this problem.

**Comment by khavrenko** [comment]
moved to https://github.com/iee/org.eclipse.iee.editor
