### ISSUE TITLE
Описать формат данных

### ISSUE THREAD

**Issue by disovi** [iee/Position-Manager#2]
Формат контейнера:
<static_begin_mark>
[header]
<static_delimiter_1>
[header content]
<static_delimiter_2>
[editor content]
<static_end_mark>

Формат заголовка (header):
<protocol_name>/<protocol_version>
<key_1> : <value_1>
<key_2> : <value_2>
...

Подробности https://github.com/iee/Position-Manager/wiki/Формат-данных-контейнера

**Comment by khavrenko** [comment]
not actual
